name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment only when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The environment that GitHub Actions will use for the job

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up Pages deployment
      - name: Set up GitHub Pages
        uses: actions/configure-pages@v3

      # Step 3: Upload static site files to GitHub Pages
      - name: Upload site files
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Upload everything in the current directory

      # Step 4: Deploy site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
